name: Continuous Integration

on: push

env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: root

jobs:
  run_code_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...

      - name: Setup MySQL and Create Database
        run: |
          mysql -e "ALTER USER '${{env.DB_USER}}'@'localhost' IDENTIFIED BY '${{env.DB_PASSWORD}}';"
          mysql -e "CREATE DATABASE IF NOT EXISTS ${{env.DB_NAME}};"

      - name: Run tests
        run: go test ./...
